# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topic
    url: /
    weight: 20
  - name: User
    url: /
    weight: 30
